### ISSUE TITLE
Allowing Initial Character Selection With Mouse Click

### ISSUE THREAD

**Issue by notzoom** [Algorithmus/DiasporicCrypt#4]
I think that would be more intuitive to have in addition, right now you have to press the right key.

Would love to hear your thoughts !

**Comment by Algorithmus** [comment]
I'm not sure if I would consider that intuitive because that would imply that the game works with the mouse, which it doesn't. It's a largely button controlled game, either with a keyboard or a gamepad. I don't want people to think that because you can select characters with the mouse that the mouse actually plays any part in the rest of the game because it doesn't really, other than default out of the box behaviors provided by Godot like text scrolling.

**Comment by notzoom** [comment]
Ok yeah that makes sense. What about allowing the first character to be selected if you press the left click ? Why does the initial selection signal has to be the right one ?

**Comment by Algorithmus** [comment]
Spatially, the selection cursor is directly above the left character, so I thought the down button made more sense. But if it's not that obvious, then I can add the left button as well.
